### ISSUE TITLE
Suggestion - display percent uploaded in browser tab title 

### ISSUE THREAD

**Issue by Larsene** [e-alfred/flowupload#11]
Display the uploaded percentage in the browser tab. This will help a lot when you're working in multitabs (one tab for files, one for music, one for flowupload)

Perhaps you can also change the icon (as in mail app when you received a new mail) when the upload is finished.

Anyway, thanks for this great NextCloud App !

**Comment by TessyPowder** [comment]
I am working on a Pull request to implement that feature.

**Comment by TessyPowder** [comment]
(the feature is actually done, i will create a Pull Request if my current PR gets merged)

**Comment by e-alfred** [comment]
Implemented with https://github.com/e-alfred/flowupload/pull/62 thanks to @TessyPowder!
