### ISSUE TITLE
Doesn't work/upload

### ISSUE THREAD

**Issue by Ammar7347** [e-alfred/flowupload#12]
Hi,

I am trying to use flowupload for nextcloud. The plugin itself sounds cool but for me it'snot working. Whenever I select a file and hit upload, it never uploads!

See the .gif I made to further clarify. https://i.imgur.com/Lz5T6ZL.gifv

**Comment by e-alfred** [comment]
It seems like the folder Flowupload needs wasn't created. Can you create a folder named "flowupload" in the root of your Nextcloud and retry the upload?

**Comment by Ammar7347** [comment]
Thanks for your reply. The folder is already here at "/var/www/nextcloud/apps/flowupload" but as you said the "root" directory so I created a folder names "flowupload" in /var/www/nextcloud" with perms 755 and it didn't work. Any other solution maybe?

**Comment by e-alfred** [comment]
No, not in the apps folder/webserver folder, I meant in the webinterface of Nextcloud. This folder has to exist because it is hardcoded currently.

From your gif:

![image](https://user-images.githubusercontent.com/10073629/35769619-e4d32f36-090d-11e8-9662-893add6b7860.png)

This is where the folder is missing.

**Comment by Ammar7347** [comment]
Thanks for the prompt reply but unfortunately it's still not working. Here's the image : https://4mm4r.ga/img/1517684789.png

**Comment by e-alfred** [comment]
Do you see anything in the logs of your installation? Are you using Nextcloud 13?

**Comment by Ammar7347** [comment]
Where can I find the logs of my installation? I was using the previous stable version of Nexcloud but now Nextcloud 13 has been released(stable) so I updated it to Nexcloud 13 but It's still not working o the Nextcloud 13.

**Comment by e-alfred** [comment]
You should find the logs either in the admin section of Nextcloud or in the file data/nextcloud.log in your Nextcloud folder.

**Comment by Ammar7347** [comment]
I checked the logs but unfortunately, there was nothing I could find. But here is the log file for the reference maybe you can find something. 
[nextcloud.log](https://github.com/e-alfred/flowupload/files/1707394/nextcloud.log)

**Comment by e-alfred** [comment]
I looked through the log but this one only shows that it was disabled/re-enabled while upgrading. Can you start a browser console and try to upload something? It might log some error if the upload fails.

**Comment by samsonle1809** [comment]
Hi @e-alfred ,
I have the same problem. I'm using S3 as primary storage and I see some error messages in my Nextcloud log: 

```
"message":"mkdir(): No such file or directory at \/var\/www\/html\/custom_apps\/flowupload\/ajax\/upload.php#37"

"message":"opendir(\/var\/www\/html\/data\/admin\/.flowupload_tmp\/): failed to open dir: No such file or directory at \/var\/www\/html\/custom_apps\/flowupload\/ajax\/Flow\/Uploader.php#17"

"message":"move_uploaded_file(\/var\/www\/html\/data\/admin\/.flowupload_tmp\/\/887c661970fa788c925b0ac5d3d0e92ead6ba7fa_1): failed to open stream: No such file or directory at \/var\/www\/html\/custom_apps\/flowupload\/ajax\/Flow\/File.php#231"
```
Can you help me?

**Comment by e-alfred** [comment]
@samsonle1809 S3 is an external storage which is currently not supported by Flowupload.

**Comment by TessyPowder** [comment]
I think this issue can be closed

**Comment by e-alfred** [comment]
This issue is pretty old without much useful information. I too think that it should be closed.
