### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by anesti222** [e-alfred/flowupload#126]
Hi, recently update flowupload to the newest version and seems to crash Nextcloud when i start to upload some files, after 2-3 songs Chrome gives an error: SBOX_FATAL_MEMORY_EXCEEDED
Before update everything works fine, now i using Nextcloud 18.0.4 version.
Is any way to use again the previous version of flowupload?
THANKS

**Comment by TessyPowder** [comment]
Yes you can use previous versions of flowupload, but you will have to install them manually.

The only Version supporting Nextcloud 19 ist the newest, so you will have to use the newest flowupload version at some point.

How much RAM does the computer running chrome have ?
Have you tried a different browser ?
Wich operating system are you using ?

We changed a lot in the newest version. (Its a rewrite), so memory consumption might have increased.

**Comment by TessyPowder** [comment]
Can you send a screenshot of the error ?

**Comment by anesti222** [comment]
> Can you send a screenshot of the error ?
![Στιγμιότυπο οθόνης (156)](https://user-images.githubusercontent.com/67975890/87202401-27ea2600-c309-11ea-9762-2c4c5081a1b3.png)
the pc has 16 GB ram, the same doin with internet explorer

**Comment by TessyPowder** [comment]
Can you open the Dev Tools and send a screenshot of the console output ?

**Comment by anesti222** [comment]
where i found Dev Tools? Nextcloud runnin from rental server not in home

**Comment by anesti222** [comment]
maybe this? https://nx10056.your-storageshare.de/ocs/v2.php/apps/serverinfo/api/v1/info

**Comment by anesti222** [comment]
![Στιγμιότυπο οθόνης (158)](https://user-images.githubusercontent.com/67975890/87207997-0f343d00-c316-11ea-9cd3-4c29fea53fa4.png)

**Comment by TessyPowder** [comment]
Sorry, but i meant the dev tools of the Browser.
You can open it by: open flowupload in the Browser, right click, select Inspect, and click on Console (in the Menu that just opened)

**Comment by anesti222** [comment]
> Sorry, but i meant the dev tools of the Browser.
> You can open it by: open flowupload in the Browser, right click, select Inspect, and click on Console (in the Menu that just opened)

[](url)
![Στιγμιότυπο οθόνης (160)](https://user-images.githubusercontent.com/67975890/87355566-464e5c80-c569-11ea-9855-1bc6764895c9.png)

**Comment by e-alfred** [comment]
Does this problem also appear with another browser if you try to upload the same files using Flowupload?

**Comment by anesti222** [comment]
Now is workin fine with chrome,problem solved don't know how,Thanks
