### ISSUE TITLE
Select Folder feature in Internet Explorer

### ISSUE THREAD

**Issue by geokh** [e-alfred/flowupload#13]
![capture](https://user-images.githubusercontent.com/35292731/34765402-4a6322da-f5e9-11e7-8aa8-2f3aa9fb66b8.JPG)

Select Folder cant be found on Internet Explorer .

Please let us know.

**Comment by e-alfred** [comment]
Folder upload is only supported on Chromium-based browsers at the moment. I will take a look into using an updated version of ng-flow which would add support for Edge and Firefox. Folder upload using Internet Explorer won't be supported even with this release except somebody provides code for that which would be welcome.
