### ISSUE TITLE
Update for NC 20?

### ISSUE THREAD

**Issue by nsturtz** [e-alfred/flowupload#182]
first I would like to say Thank you, next I would like to ask will there a version for NC 20?

**Comment by JonathanTreffler** [comment]
I have not tested flowupload on Nextcloud 20 yet. Have you ?
Does it work on Nextcloud 20 or will there be things, that need to be changed ?

This repository is maintaned and @e-alfred and me will definitily make sure it runs on Nextcloud 20.
But if big changes are necessary it might take a while.
Because i only used modern APIs in the Rewrite #73 i don't expect big problems.

**Comment by nsturtz** [comment]
I had to go back because of issues internal on my server and I need to have a sable platform.

**Comment by JonathanTreffler** [comment]
Nextcloud 20 is released, i will beginn testing this app on nextcloud 20 in the next days. I think we will be able to create a release in the next week. (@e-alfred)

**Comment by nsturtz** [comment]
I am updating now!!

**Comment by nsturtz** [comment]
Also when I did use it @e-alfred @JonathanTreffler, I had no issues with Flowupload.

**Comment by e-alfred** [comment]
If no serious bugs are found, we can do a release in the next few days.

**Comment by nsturtz** [comment]
That is great, I am having installation issues but I am trying to work them out.
https://help.nextcloud.com/t/internael-server-error-after-update-to-20-00/94076/2

**Comment by nsturtz** [comment]
I just got the issues fixed. I am going to test Flow upload to see if I can find any issues.

**Comment by nsturtz** [comment]
I have not found any issues

**Comment by nsturtz** [comment]
I just uploaded about 17K files over the course of today and I have not ran into any issues

**Comment by e-alfred** [comment]
As there are no serious issues found, I will create a release for Nextcloud 20 as soon as possible.

**Comment by e-alfred** [comment]
Flowupload 1.1.0 is released now supporting Nextcloud 20. Have fun!

**Comment by nsturtz** [comment]
Thank you @e-alfred
