### ISSUE TITLE
Slow FlowUpload Speed

### ISSUE THREAD

**Issue by markmetroit** [e-alfred/flowupload#184]
Steps to reproduce
Upload 5.1GB iso file via Browser upload, 1h 12mins
![image](https://user-images.githubusercontent.com/69255219/93331007-9078e600-f817-11ea-81e2-e49b14ddbbaf.png)

Upload 5.1GB iso file via FlowUpload.  at 1h12mins it is at 49%
![image](https://user-images.githubusercontent.com/69255219/93331033-9a9ae480-f817-11ea-8ad1-ad5c42fa4383.png)

Issue  : Files uploaded via FlowUpload used to be 3 times faster than Browser upload. Now half as fast
This was a clean install as I was having the same issue on a v17 nextcloud
This has been tested on my home slow but reliable Internet.  Issue first noticed on Office 200/200mb

Expected behaviour
Expected FlowUpload to be as fast, or faster than html5 Browser upload

Server configuration
Operating system: Centos 7

Web server: Apache2

Database: MariaDB

PHP version: 7.3.22

Nextcloud version: (see Nextcloud admin page) 19.0.3

Updated from an older Nextcloud/ownCloud or fresh install: Clean install
Where did you install Nextcloud from: Nextcloud Official Page

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed

No errors have been found.

**Comment by JonathanTreffler** [comment]
Nextcloud probably made many improvements to the upload speed.

I rewrote the entire backend so it can run on Nextcloud 19, but the performance should not have changed much.

If i have time someday i would like to add admin settings to set the chunk size and how many chunks get uploaded at the same time.
You can currently only change these options in the apps source files.
By tweaking these parameters a LOT of speed could be gained in reliable networks.
But we cannot make these changed to the app by default, because it will slow down unreliable connections.

Could you capture the actual speed of the upload (with taskmanager ...) ?

Flowupload was not exactly created for speed but for reliability, the ability to pause uploads and to continue uploads even if the browser crashed (...). But of course we want to optimize the speed.

I may try this myself to see if this a error with your instance.

**Comment by markmetroit** [comment]
Hi, I think back in NC15 it was extremely faster than the browser upload.  then on 16 I noticed it wasnt as fast so I installed a clean NC19 and the speed was the same as on 16.  my connection is a solid 200mb/s leased line(symetric)
![image](https://user-images.githubusercontent.com/69255219/93488166-f3dd4380-f8fd-11ea-9c94-a7ea666e1a74.png)

**Comment by JonathanTreffler** [comment]
It lokks like you connection cannot be completely maxed out with only 4 * 1 MB chunks at the same time.

**Comment by markmetroit** [comment]
I get similar speeds from my Home Internet which is 100/10mb.

**Comment by danger89** [comment]
I also get very very slow upload speeds!?

**Comment by markmetroit** [comment]
Is there a way I can edit my local files to enable the app to MAX out a 100mb connection?

**Comment by JonathanTreffler** [comment]
> Is there a way I can edit my server files to enable the app to MAX out a 100mb connection?

Currently not, but you can open a feature request issue here.

**Comment by danger89** [comment]
OK. I fixed it, I just created by own GUI application from scratch. v1.0. It allows you to upload fast, stable and large files from your computer to any Nextcloud server (or other WebDav apps).

Project Repo: https://gitlab.melroy.org/melroy/nextcloud-file-drop

[Download the deb file](https://gitlab.melroy.org/melroy/nextcloud-file-drop/uploads/fbcb2d35ec9091dc92f6222e81c49b74/filedrop_1.0_all.deb).

Have fun!

**Comment by JonathanTreffler** [comment]
> OK. I fixed it, I just created by own GUI application from scratch. v1.0. It allows you to upload fast, stable and large files from your computer to any Nextcloud server (or other WebDav apps).


Well that's not a "fix" but just a way to access Nextcloud over WebDAV. On linux mounting WebDav is built into the OS.
Your technique is quite different from this app. This App uses chunks so uploads can be resumed.

**Comment by JonathanTreffler** [comment]
I will add a guide how to increase and decrease the uploadsspeed of this app to the README.
Its not as good as a admin setting, but for the meantime better thatn nothing.

**Comment by danger89** [comment]
> Well that's not a "fix" but just a way to access Nextcloud over WebDAV. On linux mounting WebDav is built into the OS.
> Your technique is quite different from this app. This App uses chunks so uploads can be resumed.

I agree, however for me it's the best solution for now and works great! My file drop app is really fast.

**Comment by JonathanTreffler** [comment]
markmetroit and i tested it: Increasing the chunkSize and simultaneousUploads works pretty well.
