### ISSUE TITLE
Used space

### ISSUE THREAD

**Issue by raudraido** [e-alfred/flowupload#22]
Nextcloud wont count storage space to files which has been uploaded thru flowupload. Indicator stays the same on the left bottom corner.

**Comment by Larsene** [comment]
already reported here : [https://github.com/e-alfred/flowupload/issues/8](https://github.com/e-alfred/flowupload/issues/8), but e-alfred said it works.

it doesn't work on my system too, but i'm using nextcloudpi, not the original project, so....

**Comment by e-alfred** [comment]
I added a fix for this problem that should fix this in the latest release. Please test it and tell me if there are any problems.
