### ISSUE TITLE
Nextcloud 14 - drop of deprecated APIs

### ISSUE THREAD

**Issue by MorrisJobke** [e-alfred/flowupload#23]
Hi just want to inform you that with 14 we will drop for example `linkTo*` methods of `OCP\Util` nextcloud/server#8811

See the PHPDoc in that class for how to handle this now.

Please also have a look at nextcloud/server#7827 for other dropped methods or use the app:code-check to highlight deprecated methods in the current code.

**Comment by e-alfred** [comment]
OCP\Util deprecation should be fixed with https://github.com/e-alfred/flowupload/commit/c8048f05d3ba8a1951b3ab8a4fdd5bfa5d5e76b9. I will leave this open if further changes are needed.
