### ISSUE TITLE
antivirus integration

### ISSUE THREAD

**Issue by Django-BOfH** [e-alfred/flowupload#29]
An integration of Flow Upload into or with [Antivirus App for files](https://github.com/nextcloud/files_antivirus) would be a desirable option!

**Comment by TessyPowder** [comment]
I think a integration is not needed, but i didn't test it. Antivirus probably just listenes for file changes and flowupload sends the needed signals/events for the antivirus to know when a file got uploaded

**Comment by e-alfred** [comment]
@TessyPowder I think that sums it up pretty much. The Antivirus app already does that it seems: 

https://github.com/nextcloud/files_antivirus#features

> When the user uploads a file, it's checked

Additionally, this is probably an additional issue that seems to be related to this kind of feature: https://github.com/nextcloud/files_antivirus/issues/71

Personally, I am not quite a fan of this app plus ClamAV, it can eat up a lot of memory and cause a lot of OOM kills on a server.
