### ISSUE TITLE
upload spinner keeps spinning forever. even if UL had ended successfully

### ISSUE THREAD

**Issue by JimmyKater** [e-alfred/flowupload#32]
### Steps to reproduce
1. Upload files with >750 mb to an external storage (connected via webDAV)
2. wait
3. watch the spinner spinning

### Expected behaviour
umm. it would be nice if the spinner would stop after finishing.

### Actual behaviour
the spinner spins round and round for hours and hours - it still spins while i'm writing this (and it was finished some 7 hrs ago)

## Server configuration detail

**Operating system:** Linux 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l

**Webserver:** Apache/2.4.25 (Raspbian) (fpm-fcgi)

**Database:** mysql 10.1.23

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since several versions 

**Where did you install Nextcloud from:** back then in the beginning? I think i flashed it from NCP - ownyourbits

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - apporder: 0.4.1
 - audioplayer: 2.3.0
 - bookmarks: 0.11.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - drop_account: 0.0.6
 - dropit: 0.1.1
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_rightclick: 0.7.0
 - files_sharing: 1.5.0
 - files_snapshots: 0.1.1
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.7
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.3.2
 - ownbackup: 17.5.0
 - password_policy: 1.3.0
 - phonetrack: 0.2.7
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - rainloop: 5.0.6
 - ransomware_protection: 1.1.0
 - registration: 0.4.2
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.2.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_versions
 - radio
 - survey_client
 - systemtags
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "1": "192.168.xxx.yyy",
        "2": "nextcloud.local",
        "4": "blabla.blabla.de",
        "5": "you.wish.youd.know.de"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/blabla.blabla.de",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": "2",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "log_type": "file",
    "defaultapp": "apporder"
}
```
</details>

**Are you using external storage, if yes which one:** another webdav-service (magentacloud)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** nopers

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/43.3.3.185 Chrome/43.0.2357.81 Safari/537.36

**Operating system:** Win 7 (64) pro

**Comment by e-alfred** [comment]
External storages are not well tested at the moment. Do you have the flowupload folder on an external storage?

**Comment by JimmyKater** [comment]
no. the flowuploadfolder is in the main directory. so i moved files from there to an external storage (connected via webdav)

**Comment by Somebodyisnobody** [comment]
I have a similar problem, maybe the same trigger. https://help.nextcloud.com/t/nothing-happen-when-finished-uploading/39731

**Comment by e-alfred** [comment]
@JimmyKater Can you test the latest Flowupload app against the latest Nextcloud release (17) to check if this problem still exists?

**Comment by JimmyKater** [comment]
@e-alfred 

sorry it took me so long to see your question here... 
and again sorry i can't test it on NC17, yet as i'm not running it, yet. 

but i did test it on nc 16.0.6. and it worked well. no spinning wheel anymore after UL of 1.1GB

**Comment by TessyPowder** [comment]
Can we close this or does the issue still exist ?

**Comment by e-alfred** [comment]
Given that this issue is extremely old now and @JimmyKater said it works well on recent Nextcloud versions, i think we can close it for now. If somebody still has this problem, please add a comment and we can reopen it if necessary.
