### ISSUE TITLE
Suggestion: Let User choose where to upload

### ISSUE THREAD

**Issue by jamfx** [e-alfred/flowupload#4]
Hi,
this is not an Issue, just a Feature-Wish. I would love to "flow-upload" files, in the current folder I am in or let me Choose where to upload them somewhere. This would be great.
Thanks!
JamFX

**Comment by Larsene** [comment]
a big +1 with this suggestion !

**Comment by Wolvan** [comment]
This is an important feature for my workflow. I need the files uploaded to go into a special folder for each user, hope this can be implemented quickly.

**Comment by re83** [comment]
Agreed, please implement this feature.

**Comment by jamfx** [comment]
Are there any news about this?

**Comment by e-alfred** [comment]
This will probably be solved by https://github.com/e-alfred/flowupload/pull/31 from @NastuzziSamy. If you want to help, you can test it and report any problems back there.

**Comment by dave-sausages** [comment]
+1 for wanting this feature too. Would make things sooo much easier

**Comment by NastuzziSamy** [comment]
I'll work on it this weekend https://github.com/e-alfred/flowupload/pull/31

**Comment by rarapost** [comment]
+1 I also miss this option

**Comment by raudraido** [comment]
+1 Also miss this option!

**Comment by RafDeCoster** [comment]
Also in favor for this feature

**Comment by e-alfred** [comment]
This issue will be fixed by https://github.com/e-alfred/flowupload/pull/73 thanks to @TessyPowder, please help us test it to find any bugs.
