### ISSUE TITLE
Support for dark theme

### ISSUE THREAD

**Issue by Lappro** [e-alfred/flowupload#41]
### Steps to reproduce
1. Enable dark theme (since Nextcloud 14)
2. Open the flow upload screen
3. Drop a few files to be uploaded

### Expected behaviour
Good contrast in the "to do" table of files to upload.

### Actual behaviour
Every other item in the "to do" table has a white background with white text, making it very hard to read.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
14.0.3

### Client configuration
**Browser:**
Firefox Developer Edition version 63.0b13 (64-bit)

**Operating system:**
Windows 10

### Screenshot
![2018-10-12 20_07_27-](https://user-images.githubusercontent.com/1727604/46886241-9d864100-ce5a-11e8-8150-420cef58fe9d.png)

**Comment by e-alfred** [comment]
Yes, the dark theme is a new feature from NC14+ and is pretty much untested yet with Flowupload. I will have to take a look into it.

**Comment by e-alfred** [comment]
This is fixed by https://github.com/e-alfred/flowupload/pull/53.

**Comment by TessyPowder** [comment]
Actually the issue persists (tested in NC 16 in Dark Mode)
