### ISSUE TITLE
Support upload to an external storage

### ISSUE THREAD

**Issue by sparrowjack63** [e-alfred/flowupload#46]
Hello,

Nice App, work well on Nextcloud 15 but upload to an "external storage" seems not to be available.
Is there a way to do it or implement it ?

Thanks,

**Comment by hezten** [comment]
👍

**Comment by TessyPowder** [comment]
It would probably nice to implement this Feature into #31

**Comment by TessyPowder** [comment]
I implemented external storage support into #73 , but testing if it works well isn't done yet.

**Comment by bsommerhalder** [comment]
@TessyPowder I would be willing to test any solutions. I currently have S3 set up as primary storage (ie, not connected via External Storages app) and I receive an error trying to upload any files. Potentially relevant logs attached.
[nextcloud.log](https://github.com/e-alfred/flowupload/files/4049239/nextcloud.log)

**Comment by TessyPowder** [comment]
@bsommerhalder Wich Version of flowupload do you use ? The newest from the store or the code from my PR ?

**Comment by bsommerhalder** [comment]
@TessyPowder The newest stable from the store at the moment.

**Comment by bsommerhalder** [comment]
@TessyPowder It may also be relevant to note that my Nextcloud instance was installed using the snap.

**Comment by TessyPowder** [comment]
It would be very nice if you could test my newest version of flowupload, that is not ready for merge yet, on your nextcloud instance.
To do that just download [this](https://github.com/TessyPowder/flowupload/archive/multiple-locations.zip) zip file and replace the flowupload folder in the apps folder on your nextcloud with the content of this archive.

**Comment by bsommerhalder** [comment]
@TessyPowder I have tried this - when I overwrite the contents of the "flowupload" folder with the contents of the folder in your ZIP file, my Nextcloud "crashes" (tells me that I need to perform an update, however no update is available -- this is corrected when I revert to the backup flowupload folder). Note that I am no longer using a snap-installed version of Nextcloud, and I am currently using Nextcloud v18.

**Comment by TessyPowder** [comment]
This is happening because the app version code changes when you replace it.
I will change the version code in my development version to the newest from the store and it will work.

**Comment by TessyPowder** [comment]
It should now work (you will have to re-download the zip archive)

**Comment by bsommerhalder** [comment]
@TessyPowder Thank you, I am now using this latest version and I no longer receive the issue. And now, when I attempt to upload a file, it does upload to completion and it appears to have worked. However, the file then disappears -- it does not actually appear in the "flowupload" folder, and when I look in my S3 bucket I can see that it is not there. Here is a log: 

[nextcloud.log](https://github.com/e-alfred/flowupload/files/4160579/nextcloud.log)

**Comment by daleosm** [comment]
Hello, I found this from [here](https://github.com/e-alfred/flowupload/issues/46) as I'm also using S3 as my primary storage on my Nextcloud instance. I have also tried your zip in the mentioned thread and received the same problem as  bsommerhalder. Do you have a fix as of yet? 

I would be happy help in anyway as the native uploads in Nextcloud only provides 500kb/s whilst flowupload will upload at 1mb/s (My ISP upload limit) It's a strange quirk that I can't quite fathom

**Comment by e-alfred** [comment]
This issue will be fixed by https://github.com/e-alfred/flowupload/pull/73 thanks to @TessyPowder, please help us test it to find any bugs.

**Comment by TessyPowder** [comment]
#73 will get merged very soon and it will generally support External Storages, but problems might still appear. I will fix those in a later Pull Requests
