### ISSUE TITLE
No message "Completed" after upload

### ISSUE THREAD

**Issue by BurkhardFS** [e-alfred/flowupload#48]
### Steps to reproduce
1. Select file or folder to upload with flowupload
2. Pressing the green button "Upload"
3. Upload starts

### Expected behaviour
After upload is completed there should be a message "Completed" in the progress column.

### Actual behaviour
There are again the buttons "Pause" and "Cancel" to see.

### Server configuration

**Operating system:** Debian 8.11

**Web server:** Apache 2.4.10-10

**Database:** MySQL 5.5.62

**PHP version:** 7.2.13

**Nextcloud version:** 14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 13

**Where did you install Nextcloud from:** webinstall-script

**Signing status:**
<details>
<summary>No errors hav been found</summary>
</details>

**List of activated apps:**
<details>
<summary>Accessibility	1.0.1
Activities for shared file downloads	1.3.0
Activities for shared file downloads, visible to all admins	1.3.1
Activity	2.7.0
Admin notifications	1.0.2
Announcement center	3.3.1
AppOrder	0.6.0
Auditing / Logging	1.4.0
Brute-force settings	1.3.0
Camera RAW Previews	0.6.3
Can I update?	0.2.0
Checksum	0.4.2
Collaborative tags	1.4.0
Comments	1.4.0
Custom CSS	1.2.0
Data Request	1.1.0
Deleted files	1.4.1
DICOM Viewer	1.1.0
External sites	3.1.0
External storage support	1.5.0
Federation	1.4.0
File access control	1.4.0
File sharing	1.6.2
Files automated tagging	1.4.0
Files Right Click	0.11.0
First run wizard	2.3.0
Flow Upload	0.0.9
Group folders	2.0.2
Impersonate	1.1.0
LDAP user and group backend	1.4.0
Link editor	1.0.9
Log Reader	2.0.0
Monitoring	1.4.0
Nextcloud announcements	1.3.0
Notifications	2.2.1
OwnBackup	18.11.0
Password policy	1.4.0
PDF viewer	1.3.2
QOwnNotesAPI	18.11.0
Quota warning	1.3.0
Ransomware protection	1.2.0
Share by mail	1.4.0
Support	1.0.0
Terms of service	1.0.3
Text editor	2.6.0
Theming	1.5.0
Update notification	1.4.1
Usage survey	1.2.0
User usage report	1.1.1
Versions	1.7.1
Video player	1.3.0</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>

```
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'my.domain.com',
  ),
  'datadirectory' => '/home/nextcloud-data',
  'tempdirectory' => '/home/nextcloud-temp',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'https://my.domain.com',
  'dbname' => 'mydbname',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'myprefix_',
  'dbuser' => 'mydbuser',
  'dbpassword' => 'mydbpassword',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'log_type' => 'file',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'defaultapp' => 'announcementcenter',
  'quota_include_external_storage' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'myaddress',
  'mail_domain' => 'mydomain.com',
  'mail_smtphost' => 'exchange.mydomain.com',
  'mail_smtpport' => 'myport',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpsecure' => 'tls',
```
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** sftp.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.

### Client configuration
**Browser:** Chrome Version 71.0.3578.98 (64-Bit) OR Firefox 64.0.2 (64-Bit)

**Operating system:** Windows 10 Enterprise

#### Web server error log
<details>
<summary>No related errors</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>No entries</summary>
</details>

**Comment by mbarczak** [comment]
The same problem can be observed on Nextcloud 15.0.4

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/flowupload/commit/e0d5957415b3bfce4810b4a1c27109beda03d165
