### ISSUE TITLE
Buttons "pause" and "cancel" stay on the screen after upload

### ISSUE THREAD

**Issue by rarapost** [e-alfred/flowupload#49]
after uploaded, buttons "pause"  and "cancel" stay on the screen, which is confusing. There is no indication of succesfull upload. 

It would be great when the icons change to "OK" or somethink like this. 
I treat it as an issue, because it is not clear whether upload finished or not (and how). 

nextcloud 15.0.2, flowupload app version 0.0.9

It may relate to #48

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/flowupload/commit/e0d5957415b3bfce4810b4a1c27109beda03d165.
