### ISSUE TITLE
Feature Request: peserve upload status after leaving app page 

### ISSUE THREAD

**Issue by rarapost** [e-alfred/flowupload#50]
When I leave application page and then return back, the initial state is alays shown.

It would be great to peserve upload status after leaving app page to be able to see it in case long uploads when I return to the app.

Tle upload status could be cleaned either manually, or after certain time after upload finished (couple of hours).

**Comment by TessyPowder** [comment]
Am i getting that right:  you want to be able to resume a file upload after leaving the Flowupload Page ?
Or should the upload continue while not on the Flowupload page ?

(I am not an english native speaker so i want be sure i understand you correctly)

**Comment by ratermir** [comment]
The seconf of your questions is my idea: When I start long upload, and if I leave the "flow upload" application (but stay in Nextcloud context - for example move to the "files" app), then to continue uploading. and after I return to the "flow upload" page, show the status about proccess and finished uploads. 

I don't know whether this is possible to do it. But if it is, it will be very goof from user (= my :) ) perspective.

Btw I also am  not native english :)

**Comment by TessyPowder** [comment]
I think there isn't a better solution, that opening the files app in another tab.
Nextcloud is not a Single Page Application -> all JavaScript gets stopped when navigation to another app. So i don't think this is possible to implement

**Comment by TessyPowder** [comment]
I thought more about this and i still think this feature is not possible to implement.
I will close this now, but thanks for the feature request anyways.
