### ISSUE TITLE
Summary uploading progress bar

### ISSUE THREAD

**Issue by zpintar** [e-alfred/flowupload#51]
It will be nice to have some summary uploading progress bar on top of the file list.

When we uploading very long list of files it is hard to conclude how many of uploads is left. With this progress bar users can get good feeling about whole uploading progress.

**Comment by TessyPowder** [comment]
#57 I have added a PR

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/flowupload/pull/57.
