### ISSUE TITLE
Bug - Reclic upload after (almost) all files downloaded

### ISSUE THREAD

**Issue by Larsene** [e-alfred/flowupload#6]
On a big list, clicking "upload" again to try to download the files not marked as downloaded (but the three button are presents) freeze the page, and doesn't download this files.

**Comment by TessyPowder** [comment]
What do you mean by downloading. This app is used to upload files !!!

**Comment by e-alfred** [comment]
I am not sure if this issue is even applying to current releases because it is over two years old and the description is quite unhelpful.

**Comment by TessyPowder** [comment]
> I am not sure if this issue is even applying to current releases because it is over two years old and the description is quite unhelpful.

Yes. This can probably be closed
