### ISSUE TITLE
Folder size doesn't get calculated

### ISSUE THREAD

**Issue by TessyPowder** [e-alfred/flowupload#71]
If I upload a folder with 2 files in it (53 MB) the folder shows a size of 0 KB but the files in it show the right size.

Folder:
![image](https://user-images.githubusercontent.com/28999431/68982297-b3f18f80-0806-11ea-8d40-36665f82492b.png)

inside Folder:
![image](https://user-images.githubusercontent.com/28999431/68982335-daafc600-0806-11ea-8785-6d8a753a1f3e.png)

I think this issue exists , because flowupload needs to trigger the size calculation manually.

It does it for files via: (in [ajax/upload.php](https://github.com/e-alfred/flowupload/blob/master/ajax/upload.php))
```php
OC_Hook::emit(
	\OC\Files\Filesystem::CLASSNAME,
	\OC\Files\Filesystem::signal_post_write,
	array( \OC\Files\Filesystem::signal_param_path => $result . $path)
);
```
but it doesn't seem to trigger any folder size calculation.

(tested on Nextcloud 16 only)

**Comment by TessyPowder** [comment]
\OC\Files\Filesystem::signal_param_path can be used for both files and folders.

solution would be:
It should trigger signal_param_path with the file path if its just a file.
It should trigger signal_param_path with the folder path if its a folder.

The problem is the folder path is not being send via the request:
![image](https://user-images.githubusercontent.com/28999431/68982932-1a77ad00-0809-11ea-91dd-3d2a34158fec.png)

That could probably be solved with RegEx

**Comment by TessyPowder** [comment]
> \OC\Files\Filesystem::signal_param_path can be used for both files and folders.

Unfortunately that doesn't work. I tried several other methods , but nothing works.
I just wasted hours trying to find a solution but that Nextcloud caching stuff is really weird and not documented at all (well there's a list of functions of the classes but that's also visible in the source code)

**Comment by TessyPowder** [comment]
I finally found a solution !
It's not perfect but it works like intended

```php
\OC\Files\Filesystem::touch(dirname($path) . "/.flowupload_force_cache_update");
\OC\Files\Filesystem::unlink(dirname($path) . "/.flowupload_force_cache_update");
```
... triggers a cache update.

It creates a hidden file in the upload Directory and removes it immediately. Because it gets deleted the cache watcher re-calculates the size of all parent folders.

I tried so many things (some of them were really complicated) but nothing worked except this.
Except aesthetic reasons i think this is a good enough solution.

I will integrate this fix in my current PR #73

**Comment by Tmtlihu** [comment]
don‘t use unlink。because At the same time, upload the original file and it's gone

> 我终于找到了解决方案！
> 它不是完美的，但可以按预期工作
> 
> ```
> \ OC \ Files \ Filesystem :: touch（目录名（$ path）。 “ /.flowupload_force_cache_update ”）; 
> \ OC \ Files \ Filesystem ::取消链接（目录名（$ path）。 “ /.flowupload_force_cache_update ”）;
> ```
> 
> ...触发缓存更新。
> 
> 它会在上传目录中创建一个隐藏文件，并立即将其删除。因为它被删除，所以缓存监视程序会重新计算所有父文件夹的大小。
> 
> 我尝试了很多事情（其中有些真的很复杂），但除此之外没有任何效果。
> 除美学原因外，我认为这是一个足够好的解决方案。
> 
> 我将在当前的PR [＃73中](https://github.com/e-alfred/flowupload/pull/73)集成此修复程序[](https://github.com/e-alfred/flowupload/pull/73)

don‘t use unlink。because At the same time, upload the original file and it's gone

**Comment by Tmtlihu** [comment]
> I finally found a solution !
> It's not perfect but it works like intended
> 
> ```
> \OC\Files\Filesystem::touch(dirname($path) . "/.flowupload_force_cache_update");
> \OC\Files\Filesystem::unlink(dirname($path) . "/.flowupload_force_cache_update");
> ```
> 
> ... triggers a cache update.
> 
> It creates a hidden file in the upload Directory and removes it immediately. Because it gets deleted the cache watcher re-calculates the size of all parent folders.
> 
> I tried so many things (some of them were really complicated) but nothing worked except this.
> Except aesthetic reasons i think this is a good enough solution.
> 
> I will integrate this fix in my current PR #73

don‘t use unlink。because At the same time, upload the original file and it's gone

**Comment by TessyPowder** [comment]
But the unlink deletes an empty text fil, with the only purpose to update the file cache. No userdata gets deleted

**Comment by Tmtlihu** [comment]
you used 
\OC\Files\Filesystem::unlink(dirname($path) . "/.flowupload_force_cache_update");
may happen error：
OCP\Files\NotFoundException: /mnt/e/html/nextcloud/data/admin/.flowupload_tmp not found while trying to get owner
you can test next:
`if (\Flow\Basic::save($userhome . "/files/" . $result . $path, $config, $request)) {

                // no real copy, file comes from somewhere else, e.g. version rollback -> just update the file cache and the webdav properties without all the other post_write actions
//                \OC\Files\Cache\Cache::checkUpdate($result . $path);
//                \OC\Files\Filesystem::removeETagHook(array("path" => $result . $path));


		// OC_Hook::emit(
		// 	\OC\Files\Filesystem::CLASSNAME,
		// 	\OC\Files\Filesystem::signal_post_write,
		// 	array( \OC\Files\Filesystem::signal_param_path => $result . $path)
		// );

		\OC\Files\Filesystem::touch($result . $path);

		OC_Hook::emit(
			\OC\Files\Filesystem::CLASSNAME,
			\OC\Files\Filesystem::signal_post_create,
			array( \OC\Files\Filesystem::signal_param_path => $result . $path)
		);

	}`

**Comment by TessyPowder** [comment]
If I understand that correctly, you are saying this will solve the File Cache Problem without creating and deleting a temporary text files. I literally tried to find a solution for this problem for 2 whole days, but i was not able to find a better solution.

So does this update the File Cache ? (Have you tried it ?)
```php
if (\Flow\Basic::save($userhome . "/files/" . $result . $path, $config, $request)) {
        // no real copy, file comes from somewhere else, e.g. version rollback -> just update the file cache and the webdav properties without all the other post_write actions
	\OC\Files\Filesystem::touch($result . $path);

	OC_Hook::emit(
		\OC\Files\Filesystem::CLASSNAME,
		\OC\Files\Filesystem::signal_post_create,
		array( \OC\Files\Filesystem::signal_param_path => $result . $path)
	);

}
```
I also tried emit with signal_post_create, but it didn't work.

This is the full code, that i wrote for my suboptimal, but working solution.
If your solution works, the I would be glad to implement it into my Pull Request.

**Comment by Tmtlihu** [comment]
Yes, it can。I passed the test

**Comment by TessyPowder** [comment]
Nice. I will try it myself soon and implement it into my Pull Request.
Thanks for sharing your solution 🙂

**Comment by Tmtlihu** [comment]
hey bro。
Maybe this can help you about cache
I tried to update the cache directly after "touch"
```
		\OC\Files\Filesystem::touch($result . $path);

		$uid = \OC::$server->getUserSession()->getUser()->getUID();
		$postFix = (substr($dir, -1) === '/') ? '/' : '';
		$absolutePath = \OC\Files\Filesystem::normalizePath('/'.$uid.'/files'.$dir);
		$mount = \OC\Files\Filesystem::getMountManager()->find($absolutePath . $postFix);
		$storage = $mount->getStorage();
		$internalPath = $mount->getInternalPath($absolutePath);
		$storage->getUpdater()->update($internalPath);
```

this function in "lib\private\Files\Cache\Updater.php"

**Comment by TessyPowder** [comment]
@Tmtlihu I added your code to my merge request and it works like a charm. Thanks for sharing your solution ! :)

**Comment by e-alfred** [comment]
This issue will be fixed by https://github.com/e-alfred/flowupload/pull/73 thanks to @TessyPowder, please help us test it to find any bugs.
