### ISSUE TITLE
Migrate away from AngularJS

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/flowupload#74]
AngularJS is in LTS mode currently and will be deprecated in 2021 after a 3 year period. We should move away from AngularJS to Vue probably at some point in the future.

One possible library would be to use vue-flow as an alternative:

https://github.com/shenron/vue-flow

**Comment by TessyPowder** [comment]
> to Vue

Sounds good

> https://github.com/shenron/vue-flow

Is this production ready ?
(0 releases and 24 commits)

**Comment by e-alfred** [comment]
It is just one possibility, there is an Angular based version too or even a PHP server:

https://github.com/flowjs/ngx-flow

Best option would be to use only flow.js without any dependencies like Angular and AngularJS as to minimize the amount of problems relying on 3rd party libraries altogether:

https://github.com/flowjs/flow.js

**Comment by TessyPowder** [comment]
> Best option would be to use only flow.js without any dependencies like Angular and AngularJS as to minimize the amount of problems relying on 3rd party libraries altogether:

Do you mean vue.js + flow.js (not the old currently used version) , but no ng-flow or ngx-flow wrapper ?
Because thats what i would prefer.

**Comment by e-alfred** [comment]
> Do you mean vue.js + flow.js (not the old currently used version) , but no ng-flow or ngx-flow wrapper ?

Pretty much yes, no Angular or AngularJS dependencies at all. Vue.js is pretty much the standard now for Nextcloud apps anyway.

**Comment by TessyPowder** [comment]
Because we no longer use ng-flow when #73 gets merged it should be pretty easy to migrate to vue.js

**Comment by TessyPowder** [comment]
The "bug" label should probably be removed from this issue.

**Comment by e-alfred** [comment]
Fixed by #73.
