### ISSUE TITLE
Request/question: Change name of default upload directory

### ISSUE THREAD

**Issue by bsommerhalder** [e-alfred/flowupload#78]
By default, a /flowupload/ directory is created for uploaded files. I would like to change the name of this default directory to something more descriptive and intuitive for my users, such as /UploadedFiles/, so that the uploads directory that is autogenerated for each user is called /UploadedFiles/ instead of /flowupload/

Could anyone share any insights as to how this could be accomplished? Thanks in advance for any help.

**Comment by e-alfred** [comment]
I think this will be solved with the rework done by @TessyPowder which will allow you to upload to any folder on your Nextcloud, so no fixed folder will be necessary anymore.

An ugly temporary yet highly inadvisable fix would be to edit the Flowupload directory in the code, but I do NOT recommend that.

**Comment by e-alfred** [comment]
This issue will be fixed by https://github.com/e-alfred/flowupload/pull/73 thanks to @TessyPowder, please help us test it to find any bugs.
