### ISSUE TITLE
BUG (?) - Using flowupload doesn't impact the used space on disk

### ISSUE THREAD

**Issue by Larsene** [e-alfred/flowupload#8]
Uploading files with flowupload doesn't change the used disk space value in NextCloud 12.0.3RC2

**Comment by e-alfred** [comment]
Does it work on 12.0.3 final? Did you test it?

**Comment by Larsene** [comment]
it doesn't work, but perhaps it is a bug in Nextcloud and not in flowupload, as flowupload directory appears to contain 0kb after the upload of 18Go to datas...

**Comment by e-alfred** [comment]
I tried it with 12.0.3 final. After the upload is finished, the used space counter on the left lower corner in the files app shows the new value without a problem. The same applies for the counter at the top in the personal settings page.
