### ISSUE TITLE
Replaces main Nextcloud page with badly-fitting flow-updload page

### ISSUE THREAD

**Issue by tsjordan-eng** [e-alfred/flowupload#82]
### Steps to reproduce
1. Nextcloud updat 18 to 19
2. Enable Flow-Upload
3. Got to your Nextcloud page

### Expected behaviour
Show Nextcloud Home Page

### Actual behaviour
Flow-upload page. Doesn't look pretty. Maybe it's a mobile page trying to render on a PC browser?

### Server configuration

**Operating system**: Docker Image nextcloud:19.0-rc-apache

**Web server:** Apache

**Database:** Docker image mysql:5.7

**PHP version:** ?

**Nextcloud version:** 19.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 18

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by e-alfred** [comment]
This will be fixed for Nextcloud 19 as soon as #73 is merged.
