### ISSUE TITLE
Translations seem to be messed up for Open/Remove in German

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/flowupload#88]
Hello @rakekniven,

it seems like there are some problems with the German Translation **(https://github.com/e-alfred/flowupload/blob/master/l10n/de.js):**

```
"Open" : "Benötigt keine Übersetzung. Für Android wird nur die formelle Übersetzung verwendet (de_DE)",
"Remove" : "Benötigt keine Übersetzung. Für den Desktop wird nur die formelle Übersetzung verwendet (de_DE).",
```
![image](https://user-images.githubusercontent.com/10073629/82752206-b425a580-9dbc-11ea-8678-632509ffaff2.png)

Can you change this to "Öffnen/Entfernen" instead of these redundant strings?

**Comment by rakekniven** [comment]
Hey @e-alfred , sorry for this trouble.
There is a magic at Transifex and I cannot find the cause of it :-(

Fixed.

**Comment by e-alfred** [comment]
Thanks, appreciate your help. This seems like some kind of automated Transiflex stuff.
